# Generated by Django 4.1.9 on 2023-05-24 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_taggs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='taggs',
            new_name='tags',
        ),
    ]
